export const MOCK_CHARACTERS = [
  {
    id: "actor",
    name: "Test Actor",
    isPlayer: true,
    isAlive: true,
    deathRollAdditionalDC: 0,
    maxHP: 30,
    currentHP: 30,
    maxStamina: 30,
    currentStamina: 30,
    maxStunScore: 60,
    currentStunScore: 60,
    stats: {
      speed: 6,
      craft: 6,
      luck: 6,
      empathy: 6,
      intelligence: 6,
      reflex: 6,
      dexterity: 6,
      body: 6,
      will: 6,
    },
    skills: {
      reflexSkills: {
        brawling: 3,
        smallBlades: 3,
        staffSpear: 3,
        swordsmanship: 3,
        dodgeEscape: 3,
        melee: 3,
      },
      dexteritySkills: {
        athletics: 3,
        archery: 3,
        crossbow: 3,
      },
      willSkills: {
        spellCasting: 3,
      },
    },
    status: [],
    characterArmor: {
      head: { reductions: [], maxSP: 0, currentSP: 0, encumbranceValue: 0 },
      torso: { reductions: [], maxSP: 0, currentSP: 0, encumbranceValue: 0 },
      rightArm: { reductions: [], maxSP: 0, currentSP: 0, encumbranceValue: 0 },
      leftArm: { reductions: [], maxSP: 0, currentSP: 0, encumbranceValue: 0 },
      rightLeg: { reductions: [], maxSP: 0, currentSP: 0, encumbranceValue: 0 },
      leftLeg: { reductions: [], maxSP: 0, currentSP: 0, encumbranceValue: 0 },
    },
    weapons: [],
    susceptibilities: [],
    immunities: [],
  },
  {
    id: "target",
    name: "Test target",
    isPlayer: true,
    isAlive: true,
    deathRollAdditionalDC: 0,
    maxHP: 30,
    currentHP: 30,
    maxStamina: 30,
    currentStamina: 30,
    maxStunScore: 60,
    currentStunScore: 60,
    stats: {
      speed: 6,
      craft: 6,
      luck: 6,
      empathy: 6,
      intelligence: 6,
      reflex: 6,
      dexterity: 6,
      body: 6,
      will: 6,
    },
    skills: {
      reflexSkills: {
        brawling: 3,
        smallBlades: 3,
        staffSpear: 3,
        swordsmanship: 3,
        dodgeEscape: 3,
        melee: 3,
      },
      dexteritySkills: {
        athletics: 3,
        archery: 3,
        crossbow: 3,
      },
      willSkills: {
        spellCasting: 3,
      },
    },
    status: [],
    characterArmor: {
      head: { reductions: [], maxSP: 0, currentSP: 0, encumbranceValue: 0 },
      torso: { reductions: [], maxSP: 0, currentSP: 0, encumbranceValue: 0 },
      rightArm: { reductions: [], maxSP: 0, currentSP: 0, encumbranceValue: 0 },
      leftArm: { reductions: [], maxSP: 0, currentSP: 0, encumbranceValue: 0 },
      rightLeg: { reductions: [], maxSP: 0, currentSP: 0, encumbranceValue: 0 },
      leftLeg: { reductions: [], maxSP: 0, currentSP: 0, encumbranceValue: 0 },
    },
    weapons: [],
    susceptibilities: [],
    immunities: [],
  },
];
